add autotune strength slider and use chromatic array instead of interpolation
IAHispano/Applio pull request #756
Opened 2024-09-29 11:33 UTC by Chilluminati91

When enabling autotune you can now use a slider that changes the strength of the applied effect.

## Description
Interpolate original f0 curve and autotuned f0 curve to set the strength.
Change f0-grid to use an array of chromatic frequencies between 49 - 1046hz.

2024-09-29 11:34 UTC, blaisewf commented
why not a dropdown with all the scales and then a slider with the amount of autotune? like:

![imagen](https://github.com/user-attachments/assets/72299317-d7b2-4209-86b7-6956e50107e9)

2024-09-29 11:39 UTC, Chilluminati91 commented
Not too sure whether its needed. Would require one config for each basenote + scale (major, minor, natural minor, harmonic minor, mixo-lydian, etc.) or an intelligent algorithm to calculate them. If you want that kind of flexibility and precision I think you are better off using autotune / wavestune / melodyne etc. in post.

2024-09-29 11:55 UTC, AznamirWoW commented
Dunno whether we need this slider. Strength 1 snaps f0 to the nearest note, that's fine.. but 0.5 only goes half-way?

With the new scale I can hear it actually works, but it just flattens the curve

2024-09-29 12:10 UTC, Chilluminati91 commented
It kinda depends on the skill of the original singer. If you dont have perfect pitch but want to get a slight autotune you can set the slider to 0.3 which tunes the audio enough to make it sound natural but also closer to the intended key. If you're into modern autotune rap you set it to 0.8-1.0 to get the robotic effect.

In the end it just makes the process more adjustable IF you need it, otherwise it is hidden.

2024-10-05 12:56 UTC, blaisewf requested changes
UI strings, needs to be added to english i18n, also to TTS tab

2024-10-09 17:51 UTC, Chilluminati91 commented
added!

2024-10-09 18:31 UTC, blaisewf requested changes

2024-10-09 18:31 UTC, blaisewf commented on core.py
Missing adding the new value on some parts at the bottom of the CLI

2024-10-10 20:01 UTC, blaisewf approved these changes

2024-10-10 20:01 UTC, merged